<a href="https://colab.research.google.com/github/OJB-Quantum/Notebooks-for-Ideas/blob/main/Molecular_Dynamics_Simulation_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# Bare-bones MD simulation of a graphene sheet with an MOS gate
# Uses Lennard-Jones potential for simplicity
import numpy as np

# Simulation parameters
timestep = 0.001  # in picoseconds
num_steps = 10000  # Total number of time steps

# Graphene lattice parameters
num_atoms = 100  # Number of atoms in graphene
box_size = 10.0  # Simulation box size in nm

# Lennard-Jones potential parameters for C atoms (graphene)
epsilon_C = 0.003  # Depth of the potential well in eV
sigma_C = 0.34    # Distance at which the potential is zero in nm

# Initialize atom positions (simple 2D graphene lattice)
def initialize_graphene_lattice(num_atoms, box_size):
    positions = np.zeros((num_atoms, 2))
    for i in range(num_atoms):
        x = (i % 10) * (sigma_C * 1.42)  # 1.42 is the C-C bond length factor
        y = (i // 10) * (sigma_C * 1.42)
        positions[i] = [x % box_size, y % box_size]
    return positions

# Initialize velocities randomly
def initialize_velocities(num_atoms):
    return np.random.randn(num_atoms, 2) * 0.01  # Small initial velocities

# Lennard-Jones force calculation
def lennard_jones_force(r, epsilon, sigma):
    r6 = (sigma / r)**6
    r12 = r6 * r6
    force = 24 * epsilon * (2 * r12 - r6) / r
    return force

# Update positions and velocities
def update_positions(positions, velocities, forces, dt):
    positions += velocities * dt + 0.5 * forces * dt**2
    return positions

def update_velocities(velocities, forces, dt):
    velocities += forces * dt
    return velocities

# Main simulation loop
def run_simulation():
    positions = initialize_graphene_lattice(num_atoms, box_size)
    velocities = initialize_velocities(num_atoms)
    forces = np.zeros_like(positions)

    for step in range(num_steps):
        # Calculate forces
        for i in range(num_atoms):
            force_i = np.zeros(2)
            for j in range(num_atoms):
                if i != j:
                    r_vec = positions[i] - positions[j]
                    r = np.linalg.norm(r_vec)
                    if r > 0:
                        f_mag = lennard_jones_force(r, epsilon_C, sigma_C)
                        force_i += f_mag * (r_vec / r)
            forces[i] = force_i

        # Update positions and velocities
        positions = update_positions(positions, velocities, forces, timestep)
        velocities = update_velocities(velocities, forces, timestep)

        # Periodic boundary conditions
        positions = positions % box_size

        # Print positions every 1000 steps
        if step % 1000 == 0:
            print(f"Step {step}: Positions of first 5 atoms:\n", positions[:5])

if __name__ == "__main__":
    run_simulation()


Step 0: Positions of first 5 atoms:
 [[9.99998686e+00 9.99999773e+00]
 [4.82798708e-01 2.37777573e-06]
 [9.65602938e-01 1.49945336e-05]
 [1.44839145e+00 9.99999445e+00]
 [1.93120539e+00 9.99999367e+00]]
Step 1000: Positions of first 5 atoms:
 [[9.98685883 9.99773863]
 [0.4885043  0.01073314]
 [0.96166529 0.02388742]
 [1.44653936 9.99444675]
 [1.93670272 9.99364862]]
Step 2000: Positions of first 5 atoms:
 [[9.97373079 9.99547953]
 [0.50986195 0.03999388]
 [0.94270057 0.0687145 ]
 [1.45767879 9.98887678]
 [1.9428867  9.98713598]]
Step 3000: Positions of first 5 atoms:
 [[9.96060274 9.99322042]
 [0.54811502 0.09263184]
 [0.90377491 0.11201335]
 [1.48252783 9.98325416]
 [1.95081731 9.9802435 ]]
Step 4000: Positions of first 5 atoms:
 [[9.9474747  9.99096131]
 [0.52335137 0.15590777]
 [0.91707588 0.12166599]
 [1.52368153 9.97751819]
 [1.96167197 9.97265263]]
Step 5000: Positions of first 5 atoms:
 [[9.93434666 9.9887022 ]
 [0.48342978 0.17466042]
 [0.94834791 0.14993965]
 [1.58433247 9.971